export const CONFIG = {
  api: 'http://localhost:3006',
  selectors: {
    mainContentPages: '.main .page',
    homePage: '.all-cars',
    allCars: '.single-card',
    cars: '.cars',
    btnDark: 'btn-outline-dark',
    singleCar: '.single-car',
    singlePageContent: '.one-card',
    cardTitleMain: '.card-title_main',
    cardTitleDescription: '.card-title_description',
    cardTextDescription: '.card-text_description',
    cardImg: '.single-car .card-img',
    year: '.year',
    speed: '.speed',
    engine: '.engine',
    start: '.start',
    drive: '.drive',
    price: '.price',
    warranty: '.warranty',
    btnMain: 'btn-main',
    errorPage: '.error',

  },
  none: 'none',
  block: 'block',
};