export const CONFIG = {
  api: 'http://localhost:3006',
  selectors: {
    mainContentPages: '.main .page',
    homePage: '.all-cars',
    allCars: '.single-card',
    cars: '.cars',
    btnDark: 'btn-outline-dark',
    singleCar: '.single-car',
    singlePageContent: '.single-card',
    cardTitleMain: '.card-title_main',
    cardTitleDescription: '.card-title_description',
    cardTextDescription: '.card-text_description',
    cardImg: '.single-car .card-img',
    year: '.year',
    speed: '.speed',
    engine: '.engine',
    start: '.start',
    drive: '.drive',
    price: '.price',
    warranty: '.warranty',
    btnMain: 'btn-main',
    errorPage: '.error',
    btnActivAboutPage: '.navbar-brand',
    btnAboutPage: '.btn-about',
    aboutPage: '.about',
    btnSearch: '.btn-outline-secondary',
    searchInput: '.form-control',
    searchPage: '.search',
    searchCard: '.saerch-card',
    btnInitForm: '.btn-form',
    formPage: '.form',
    formPageContent: '#connectionForm',
    customersName: '#name',
    customersEmail: '#email',
    customersPhone: '#phone',
    customersTextarea: '#textarea',
    nameError: '#name-error',
    emailError: '#email-error',
    phoneError: '#phone-error',
    btnFormRet: '.return-btn',
  },
  none: 'none',
  block: 'block',
};